/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.edu.itses.jylc.View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import mx.edu.itses.jylc.Controller.VuelosController;
/**
 *
 * @author josue
 */
public class CRUDEVuelos extends javax.swing.JFrame {

    /**
     * Creates new form CRUDEVuelos
     */
    public CRUDEVuelos() {
        initComponents();
        setLocationRelativeTo(null);

        
        
          btnAgregar.addActionListener(e ->{
          CREATEForm form = new CREATEForm();
          form.setVisible(true);
           });
        


          btnmostrar.addActionListener(e -> {
           if (VuelosController.obtenerVuelos().isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay vuelos registrados para mostrar.", "Información", JOptionPane.INFORMATION_MESSAGE);
    } else {
        ViewForm form = new ViewForm();
        form.setVisible(true);
    }
});

  
           
   
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        pnlBotones = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        lbltituloAgregar = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnmostrar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        lblEditar = new javax.swing.JLabel();
        lbMostrar = new javax.swing.JLabel();
        lblGuardar = new javax.swing.JLabel();
        lbMostrar1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Gestion de vuelos");

        btnEliminar.setText("Eliminar");

        btnAgregar.setText("Agregar");

        lbltituloAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbltituloAgregar.setForeground(new java.awt.Color(0, 0, 0));
        lbltituloAgregar.setText("Agregar");

        btnEditar.setText("Editar");

        btnmostrar.setText("Mostrar");

        BtnGuardar.setText("Guardar");

        lblEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEditar.setForeground(new java.awt.Color(0, 0, 0));
        lblEditar.setText("Editar vuelo");

        lbMostrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMostrar.setForeground(new java.awt.Color(0, 0, 0));
        lbMostrar.setText("Mostrar vuelo");

        lblGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGuardar.setForeground(new java.awt.Color(0, 0, 0));
        lblGuardar.setText("Guardar el archivo en txt");

        lbMostrar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMostrar1.setForeground(new java.awt.Color(0, 0, 0));
        lbMostrar1.setText("Eliminar vuelo");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Origen", "Destino", "Fecha", "Num Pasajeros"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBotonesLayout.createSequentialGroup()
                                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(lbltituloAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(39, 39, 39)
                                        .addComponent(lblEditar)))
                                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnmostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(lbMostrar)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(BtnGuardar))
                                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                                        .addComponent(lbMostrar1)
                                        .addGap(37, 37, 37)
                                        .addComponent(lblGuardar))))
                            .addGroup(pnlBotonesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addGap(56, 56, 56)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltituloAgregar)
                    .addComponent(lblEditar)
                    .addComponent(lbMostrar)
                    .addComponent(lbMostrar1)
                    .addComponent(lblGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEditar)
                    .addComponent(btnmostrar)
                    .addComponent(btnEliminar)
                    .addComponent(BtnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlBotones, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbMostrar;
    private javax.swing.JLabel lbMostrar1;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblGuardar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lbltituloAgregar;
    private javax.swing.JPanel pnlBotones;
    // End of variables declaration//GEN-END:variables
}
